### ISSUE TITLE
Failing to install via source

### ISSUE THREAD

**Issue by alanyee** [devsecops/restacker#18]
When I do,

```
gem build restacker.gemspec
```

I get:

```
INSTALLING RESTACKER
Invalid gemspec in [restacker.gemspec]: cannot load such file -- aws-sdk
ERROR:  Error loading gemspec. Aborting.
ERROR:  Could not find a valid gem 'restacker' (>= 0) in any repository
ERROR:  Possible alternatives: stacker, aws_tracker, bus_tracker, debsacker, geo_stalker
```

**Comment by JMeyer0101** [comment]
you may try running `bundle install` before running `gem build restacker.gemspec`.  Not sure but judging from your output you may need the aws-sdk gem installed, which bundle install should fix

**Comment by alanyee** [comment]
The bundle install seems to work, so I proposed #21 for clearer instructions for anyone else who might have this problem.
